[package]
name = "analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
ateam-controls = { path = "../ateam-controls", features = ["std"] }

[[bin]]
name = "trajectory_sim"
test = false
harness = false